version: "2"
volumes:
  docker-sync:
services:
  docker-sync:
    image: stephpr/docker-sync
    container_name: my-express-app_docker-sync
    volumes:
    - docker-sync:/sync
  my-express-app:
    build: .
    image: my-express-app:workspace
    container_name: my-express-app_workspace
    depends_on:
    - docker-sync
    volumes:
    - docker-sync:/.sync:ro
    - .:/.src
    environment:
      DOCKER_SYNC_TARGET: /app
    entrypoint: [ "/.sync/start", "/sync" ]
